### ISSUE TITLE
Adding extra tally for dose

### ISSUE THREAD

**Issue by Shimwell** [fusion-energy/openmc-dagmc-wrapper#14]
Effective dose should be added as an option on cells and 2d / 3d regular mesh tallies

This is example is for a surface but might be helpful
https://github.com/ukaea/openmc_workshop/blob/main/tasks/task_09_CSG_surface_tally_dose/1_surface_dose_from_gamma_source.ipynb

OpenMC docs on dose coefficients https://docs.openmc.org/en/stable/pythonapi/generated/openmc.data.dose_coefficients.html

ICRP publication https://journals.sagepub.com/doi/pdf/10.1016/j.icrp.2011.10.001

**Comment by Shimwell** [comment]
tally has been added but needs to be multiplied by volume to get useful units

**Comment by RemDelaporteMathurin** [comment]
I think this is now done in #60

**Comment by Shimwell** [comment]
Thanks for fixing this Remi
