### ISSUE TITLE
Method export_xml should be refactored a bit

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [fusion-energy/openmc-dagmc-wrapper#55]
Currently the method `NeutronicsModel.export_xml` is like 450 line long which makes it hard to read and also hard to override when needed.

Maybe it could be split into at least three parts as the tet_mesh_filename, mesh_tally_3D and mesh_tally_2D seem independent enough 
![image](https://user-images.githubusercontent.com/40028739/133973496-3cbc219f-fe62-4871-8307-664ffb2be482.png)

**Comment by Shimwell** [comment]
yep totally agree, this has been getting larger and larger. I did have a go at this a while back on the ```refactor_tallies``` branch but I think that can be ignored now as it is so out of date.
