### ISSUE TITLE
NeutronicsModel.export_xml() should accept a geometry argument

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [fusion-energy/openmc-dagmc-wrapper#56]
If reflective surfaces are required, the variable `geom` in `NeutronicsModel.export_xml()` needs to be modified accordingly.

Currently, the only way of achieving this is to completely override the `NeutronicsModel.export_xml()` method.

It would be more convenient if an `openmc.Geometry` object could be passed.

**Comment by Shimwell** [comment]
Yep I can do this, it is getting a bit messy having the ```.simulate``` call the ```export_xml``` method so might be best to require the user to call the ```export_xml```
