### ISSUE TITLE
bounding_box in MeshTally2D shouldn't have a default value

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [fusion-energy/openmc-dagmc-wrapper#67]
The default value of `bounding_box` in `MeshTally2D` is `None`.
However, it has to either be a string (h5m filename) or a list of tuples.
It can never be `None`, therefore, this argument shouldn't have a default value.

Running,
```python
tally = odw.MeshTally2D('(n,Xa)', plane="xz")
```
produces (on v0.2.2):
```
  File "stage_3_run_neutronics_simulation.py", line 75, in <module>
    tally = odw.MeshTally2D('(n,Xa)', plane="xz")#, bounding_box=[(800-700, -1, -700), (800+700, 1, 700)])
  File "/opt/conda/lib/python3.8/site-packages/openmc_dagmc_wrapper/Tally.py", line 318, in __init__
    self.create_mesh(bounding_box)
  File "/opt/conda/lib/python3.8/site-packages/openmc_dagmc_wrapper/Tally.py", line 394, in create_mesh
    mesh.lower_left = self.bounding_box[0]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by RemDelaporteMathurin** [comment]
I guess the same bug stands for `MeshTally3D`

**Comment by shimwell** [comment]
The bounding box functionality has been moved into a new package. I was making use of this in a few places so I thought in made sense to have it available.

We can bring it onboard as a dependency if that helps
https://github.com/fusion-energy/dagmc_bounding_box
