### ISSUE TITLE
Larger vacuum radius needed

### ISSUE THREAD

**Issue by shimwell** [fusion-energy/openmc-dagmc-wrapper#70]
I think the ```largest_radius = max(max(bbox[0]), max(bbox[1]))``` logic when setting the radius of the vacuum boundary condition is not quite correct and cuts of the corners of the geometry within the sphere. Might have to add some trigonometry here

**Comment by RemDelaporteMathurin** [comment]
I can't get my head around it but maybe a safety factor of say 3 could do the trick

**Comment by RemDelaporteMathurin** [comment]
@shimwell I think we can close this now
